DROP TABLE IF EXISTS `product`;

CREATE TABLE `product` (
    `id` VARCHAR(64) NOT NULL PRIMARY KEY COMMENT 'PK',
    `name` VARCHAR(100) NOT NULL COMMENT '상품명',
    `price` INT NOT NULL COMMENT '가격',
    `stock` INT NOT NULL COMMENT '재고수량',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자'
);

-- Sample Data
